name: HolographicShop
main: org.holographicshop.main.HolographicShop
version: 1.0.3
depend: [HolographicDisplays, Vault]
commands:
  shop:
    description: /shop
    usage: /shop
  hs:
    description: holographicshop
    usage: /hs
permissions:
    holographicshop.admin:
        description: Gives access to build adminshop
    holographicshop.user:
        description: Gives access to build usershop
    holographicshop.creativeexempt:
        description: Gives access to build adminshop
